"""initial

Revision ID: 46a0797d8fa7
Revises: 
Create Date: 2025-06-19 14:20:06.657375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a0797d8fa7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_created', sa.DateTime(), nullable=False),
    sa.Column('_lastmodified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('books',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_nonfiction', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_created', sa.DateTime(), nullable=False),
    sa.Column('_lastmodified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_created', sa.DateTime(), nullable=False),
    sa.Column('_lastmodified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors._id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books._id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_authors')
    op.drop_table('users')
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
