"""nullable_columns

Revision ID: daa49ade0391
Revises: 46a0797d8fa7
Create Date: 2025-06-19 15:46:54.094506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daa49ade0391'
down_revision: Union[str, Sequence[str], None] = '46a0797d8fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', '_lastmodified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('books', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'abstract',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', '_lastmodified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', '_lastmodified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_lastmodified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('books', '_lastmodified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('books', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'abstract',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('authors', '_lastmodified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
